Questions 54,55
trueddd/UniversityExams pull request #73
Opened 2020-03-16 15:37 UTC by melonholy

2020-03-16 16:42 UTC, trueddd commented on rsiot/rsiot.md
> +Поколько монолитная версия FTGO хранит свои данные в одной БД, она может легко извлечь подробности о заказе с помощью выражения SELECT, которая объединяет таблицы.Тогда как в микросервисном приложени
Что такое FTGO?

2020-03-16 16:42 UTC, trueddd requested changes

2020-03-16 16:42 UTC, trueddd commented on rsiot/rsiot.md
> +![img1](./54_2.png)
Разбей файлики по папкам

2020-03-16 17:02 UTC, troinoiOdekoloN commented on rsiot/rsiot.md
> +Поколько монолитная версия FTGO хранит свои данные в одной БД, она может легко извлечь подробности о заказе с помощью выражения SELECT, которая объединяет таблицы.Тогда как в микросервисном приложени
FTGO what do you mean?

2020-03-16 17:11 UTC, slavasgod commented on rsiot/rsiot.md
> +Поколько монолитная версия FTGO хранит свои данные в одной БД, она может легко извлечь подробности о заказе с помощью выражения SELECT, которая объединяет таблицы.Тогда как в микросервисном приложени
Проблемы запроса данных из нескольких сервисов - где ответ на этот вопрос?

2020-03-16 17:56 UTC, melonholy commented on rsiot/rsiot.md
> +Поколько монолитная версия FTGO хранит свои данные в одной БД, она может легко извлечь подробности о заказе с помощью выражения SELECT, которая объединяет таблицы.Тогда как в микросервисном приложени
@slavasgod Проблема в том,что если нужно выполнить один запрос,( как на картинке "найти заказ"), то нужно делать запрос на все сервисы. которые связанны с изначальным запросом

2020-03-16 18:37 UTC, VechnayaUnost commented on rsiot/rsiot.md
> +
Если ты уже пишешь, как это расшифровывается, то расписывай полностью, нет расшифровки аббревиатуры "CQRS". Добавь определение (то что ты посчитал определением - это просто перевод).

2020-03-16 18:40 UTC, VechnayaUnost commented on rsiot/rsiot.md
Расписать что такое отставание репликации

2020-03-16 18:45 UTC, VechnayaUnost commented on rsiot/rsiot.md
> +
"запорсов" ))

2020-03-17 09:32 UTC, trueddd approved these changes

2020-03-17 09:35 UTC, merged